#! /bin/sh
# ________  ________  ________  ___       __   _____ ______   ________  ________     
#|\   __  \|\   ____\|\   __  \|\  \     |\  \|\   _ \  _   \|\   __  \|\   ____\    
#\ \  \|\ /\ \  \___|\ \  \|\  \ \  \    \ \  \ \  \\\__\ \  \ \  \|\  \ \  \___|    
# \ \   __  \ \_____  \ \   ____\ \  \  __\ \  \ \  \\|__| \  \ \   _  _\ \  \       
#  \ \  \|\  \|____|\  \ \  \___|\ \  \|\__\_\  \ \  \    \ \  \ \  \\  \\ \  \____  
#   \ \_______\____\_\  \ \__\    \ \____________\ \__\    \ \__\ \__\\ _\\ \_______\
#    \|_______|\_________\|__|     \|____________|\|__|     \|__|\|__|\|__|\|_______|
#             \|_________| 


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a Xfce4-terminal state=floating
#bspc rule -a feh state=floating

bspc config normal_border_color \#D38A0C 
bspc config active_border_color \#CCCCCC
bspc config focused_border_color \#D38A0C 
bspc config presel_feedback_color \#FFFFFF

feh --bg-scale /home/nicolas/Downloads/nothing-to-see-here-3-1366×768.jpg &
picom --experimental-backends &
setxkbmap -layout br &
bash /home/nicolas/.config/polybar/launch.sh --shades

